# Generated by Django 4.2.2 on 2023-06-11 06:28

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, default='default.jpg', upload_to='media/category_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, default='default.jpg', upload_to=blog.models.product_image_upload_to)),
                ('photo_1', models.ImageField(blank=True, upload_to=blog.models.product_image_upload_to)),
                ('photo_2', models.ImageField(blank=True, upload_to=blog.models.product_image_upload_to)),
                ('photo_3', models.ImageField(blank=True, upload_to=blog.models.product_image_upload_to)),
                ('is_available', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='blog.product')),
            ],
        ),
    ]
