# Generated by Django 4.2.2 on 2023-06-11 10:12

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, default='media/default.jpg', upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='media/default.jpg', upload_to=blog.models.product_image_upload_to),
        ),
    ]
