# Generated by Django 4.2.2 on 2023-06-11 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_photo_remove_product_photo_remove_product_photo_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.product', verbose_name='Продукт'),
        ),
    ]
